[mypy]
python_version = 3.11
ignore_missing_imports = True
follow_imports = silent
exclude = (^\.venv/|^artifacts/)
disable_error_code = override,arg-type,var-annotated,attr-defined,index,union-attr,operator,assignment
